### ISSUE TITLE
feature_request(path): Multiple paths

### ISSUE THREAD

**Issue by Kristinita** [simonv3/covenant-generator#15]
### 1. Summary

It would be nice, if would be possible generate `CODE_OF_CONDUCT.md` file for multiple paths.

See also [**related issue**](https://github.com/sindresorhus/conduct/issues/7) for conduct package.

### 2. Example usage

**If**:

    covgen <example@email.com> --file CODE_OF_CONDUCT.md output/CODE_OF_CONDUCT.md

Will generate 2 `CODE_OF_CONDUCT.md` files: in root and `output` folders.

### 3. Argumentation

Example project structure:

```markdown
D:.
│   source_file
│
├───another_source_folder
├───output
│       build_file
│
└───source_folder
```

I built my project → I get content of `output` folder.

I have 1 GitHub repository for source and another repository for `output`. I need add `CODE_OF_CONDUCT.md` for source and for `output` both.

Real example:

+ Source — **<https://github.com/Kristinita/KristinitaPelican>**,
+ Content of my real `output` folder — **<https://github.com/Kristinita/Kristinita.github.io>**.

I need `CODE_OF_CONDUCT.md` for both repositories.

Thanks.

**Comment by RichardLitt** [comment]
I like this idea, although I'm not sure how common it would be to need this. You could pipe the Code to the locations using `xargs`, too. 

`> cat list_of_locations | xargs -0 covgen example@example.com --file`

I believe. Would that solve your issue? It might make more sense than adding more functionality.

**Comment by simonv3** [comment]
@RichardLitt if that works, we could add it to our readme, with an explanation of what the command means?

**Comment by RichardLitt** [comment]
We could, although I don't often see `xargs` stuff in other READMEs. It's hard to keep the scope tight when you balloon out to include features that are really part of shell scripting, and not just native to the JavaScript module in question. For instance, we could also add a section on how to edit the text using `sed`, but I don't think that is really needed here.

**Comment by simonv3** [comment]
Right, but no one has asked for support on editing the text, whereas here and on `conduct` there is a feature request for this.

**Comment by RichardLitt** [comment]
There's a request for `conduct`, too? 

Ok. I'd be happy to make a PR and write this up. I think it makes more sense than adding a feature.

**Comment by RichardLitt** [comment]
@Kristinita Would that work for you?

**Comment by Kristinita** [comment]
@RichardLitt, @simonv3, it not good solution for me, because it UNIX-specific and doesn't work on Windows without installation additional software (as Cygwin, Bash for Windows, GNU Coreutils for Windows).

I add `npx covgen <email>` command to my task runner. I need add different scripts for Windows and *NIX, that my task works. It may take a lot of time.

Thanks.

**Comment by RichardLitt** [comment]
Now there's an interesting point I hadn't considered! Ok, this makes sense as a feature to make, then. I don't have the time at the moment.

**Comment by RichardLitt** [comment]
@Kristinita This has now been enabled! Good luck! Let me know if you need help.

**Comment by simonv3** [comment]
Thank you Richard!!
