### ISSUE TITLE
use the git email config setting if it can for email

### ISSUE THREAD

**Issue by cicorias** [simonv3/covenant-generator#20]
FYI, i'm working on a PR, just putting this out there -  

essentially, if an `exec git config --get user.email` works - use that for email if nothing suppllied as an argument. otherwise, bail and normal error message about needing an amil.,

**Comment by RichardLitt** [comment]
Sounds good to me!

**Comment by RichardLitt** [comment]
@cicorias Any word on that PR?

**Comment by RichardLitt** [comment]
Opening this to anyone who wants to take it. :)

**Comment by drumenbassik** [comment]
@simonv3

**Comment by RichardLitt** [comment]
@drumenbassik Yes?

**Comment by khokho1986** [comment]
Yes

**Comment by meadowsys** [comment]
I think I'll PR

**Comment by RichardLitt** [comment]
Looking forward to it.

**Comment by khokho1986** [comment]
> FYI, i'm working on a PR, just putting this out there -  
> 
> essentially, if an `exec git config --get user.email` works - use that for email if nothing suppllied as an argument. otherwise, bail and normal error message about needing an amil.,
Khokho1986@gmail.com
    37HFTNwL3xM7kS91C27txBCGXsqB5Tn2r

**Comment by RichardLitt** [comment]
@khokho1986 You've been reported for spam.

**Comment by RichardLitt** [comment]
Done! Thanks, @autumnblazey.
