### ISSUE TITLE
Instructions to install Node-js

### ISSUE THREAD

**Issue by vipuldcoder** [simonv3/covenant-generator#28]

**Comment by bnb** [comment]
what is the question here? If you're looking for how to install Node.js I'd recommend looking at nodejs.org to directly download it or their guide on [_how to install via package manager_](https://nodejs.org/en/download/package-manager/).

**Comment by RichardLitt** [comment]
Agreed. Good luck, @vipuldcoder. Thanks, @bnb. :)
