### ISSUE TITLE
404 error when running `npx covgen`

### ISSUE THREAD

**Issue by bnb** [simonv3/covenant-generator#29]
I've used covgen for some time now, and truly love it. Running it on two different editors on two different machines (one in the cloud, one local), I'm getting the same issue:

The CLI errors out with a 404 and vomits this out to the terminal:
<details>
<pre><code>Downloading Contributors Covenant...
Error fetching file: StatusCodeError: 404 - "<!DOCTYPE html>\n<html>\n  <head>\n    <meta charset=\"utf-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\n\n    <title>Page Not Found</title>\n    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>\n    <style>\n    body {\n      font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\";\n      background: rgb(14, 30, 37);\n      color: white;\n      overflow: hidden;\n      margin: 0;\n      padding: 0;\n    }\n\n    h1 {\n      margin: 0;\n      font-size: 22px;\n      line-height: 24px;\n    }\n\n    .main {\n      position: relative;\n      display: flex;\n      flex-direction: column;\n      align-items: center;\n      justify-content: center;\n      height: 100vh;\n      width: 100vw;\n    }\n\n    .card {\n      position: relative;\n      display: flex;\n      flex-direction: column;\n      width: 75%;\n      max-width: 364px;\n      padding: 24px;\n      background: white;\n      color: rgb(14, 30, 37);\n      border-radius: 8px;\n      box-shadow: 0 2px 4px 0 rgba(14, 30, 37, .16);\n    }\n\n    a {\n      margin: 0;\n      text-decoration: none;\n      font-weight: 600;\n      line-height: 24px;\n      color: #00ad9f;\n    }\n\n    a svg {\n      position: relative;\n      top: 2px;\n    }\n\n    a:hover,\n    a:focus {\n      text-decoration: underline;\n      color: #007A70;\n    }\n\n    a:hover svg path{\n      fill: #007A70;\n    }\n\n    p:last-of-type {\n      margin: 0;\n    }\n\n    </style>\n  </head>\n  <body>\n    <div class=\"main\">\n      <div class=\"card\">\n        <div class=\"header\">\n          <h1>Page Not Found</h1>\n        </div>\n        <div class=\"body\">\n          <p>Looks like you've followed a broken link or entered a URL that doesn't exist on this site.</p>\n          <p>\n            <a id=\"back-link\" href=\"/\">\n              <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" viewBox=\"0 0 16 16\">\n                <path fill=\"#00ad9f\" d=\"M11.9998836,4.09370803 L8.55809517,7.43294953 C8.23531459,7.74611298 8.23531459,8.25388736 8.55809517,8.56693769 L12,11.9062921 L9.84187871,14 L4.24208544,8.56693751 C3.91930485,8.25388719 3.91930485,7.74611281 4.24208544,7.43294936 L9.84199531,2 L11.9998836,4.09370803 Z\"/>\n              </svg>\n              Back to our site\n             </a>\n          </p>\n        </div>\n      </div>\n    </div>\n    <script>\n      (function() {\n        if (document.referrer && document.location.host && document.referrer.match(new RegExp(\"^https?://\" + document.location.host))) {\n          document.getElementById(\"back-link\").setAttribute(\"href\", document.referrer);\n        }\n      })();\n    </script>\n  </body>\n</html>\n\n"
    at new StatusCodeError (/Users/cyren/.npm/_npx/7098/lib/node_modules/covgen/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Users/cyren/.npm/_npx/7098/lib/node_modules/covgen/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Users/cyren/.npm/_npx/7098/lib/node_modules/covgen/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/cyren/.npm/_npx/7098/lib/node_modules/covgen/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/Users/cyren/.npm/_npx/7098/lib/node_modules/covgen/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/Users/cyren/.npm/_npx/7098/lib/node_modules/covgen/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  name: 'StatusCodeError',
  statusCode: 404,
  message: `404 - "<!DOCTYPE html>\\n<html>\\n  <head>\\n    <meta charset=\\"utf-8\\">\\n    <meta name=\\"viewport\\" content=\\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\\">\\n\\n    <title>Page Not Found</title>\\n    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>\\n    <style>\\n    body {\\n      font-family: -apple-system, BlinkMacSystemFont, \\"Segoe UI\\", Roboto, Helvetica, Arial, sans-serif, \\"Apple Color Emoji\\", \\"Segoe UI Emoji\\", \\"Segoe UI Symbol\\";\\n      background: rgb(14, 30, 37);\\n      color: white;\\n      overflow: hidden;\\n      margin: 0;\\n      padding: 0;\\n    }\\n\\n    h1 {\\n      margin: 0;\\n      font-size: 22px;\\n      line-height: 24px;\\n    }\\n\\n    .main {\\n      position: relative;\\n      display: flex;\\n      flex-direction: column;\\n      align-items: center;\\n      justify-content: center;\\n      height: 100vh;\\n      width: 100vw;\\n    }\\n\\n    .card {\\n      position: relative;\\n      display: flex;\\n      flex-direction: column;\\n      width: 75%;\\n      max-width: 364px;\\n      padding: 24px;\\n      background: white;\\n      color: rgb(14, 30, 37);\\n      border-radius: 8px;\\n      box-shadow: 0 2px 4px 0 rgba(14, 30, 37, .16);\\n    }\\n\\n    a {\\n      margin: 0;\\n      text-decoration: none;\\n      font-weight: 600;\\n      line-height: 24px;\\n      color: #00ad9f;\\n    }\\n\\n    a svg {\\n      position: relative;\\n      top: 2px;\\n    }\\n\\n    a:hover,\\n    a:focus {\\n      text-decoration: underline;\\n      color: #007A70;\\n    }\\n\\n    a:hover svg path{\\n      fill: #007A70;\\n    }\\n\\n    p:last-of-type {\\n      margin: 0;\\n    }\\n\\n    </style>\\n  </head>\\n  <body>\\n    <div class=\\"main\\">\\n      <div class=\\"card\\">\\n        <div class=\\"header\\">\\n          <h1>Page Not Found</h1>\\n        </div>\\n        <div class=\\"body\\">\\n          <p>Looks like you've followed a broken link or entered a URL that doesn't exist on this site.</p>\\n          <p>\\n            <a id=\\"back-link\\" href=\\"/\\">\\n              <svg xmlns=\\"http://www.w3.org/2000/svg\\" width=\\"16\\" height=\\"16\\" viewBox=\\"0 0 16 16\\">\\n                <path fill=\\"#00ad9f\\" d=\\"M11.9998836,4.09370803 L8.55809517,7.43294953 C8.23531459,7.74611298 8.23531459,8.25388736 8.55809517,8.56693769 L12,11.9062921 L9.84187871,14 L4.24208544,8.56693751 C3.91930485,8.25388719 3.91930485,7.74611281 4.24208544,7.43294936 L9.84199531,2 L11.9998836,4.09370803 Z\\"/>\\n              </svg>\\n              Back to our site\\n             </a>\\n          </p>\\n        </div>\\n      </div>\\n    </div>\\n    <script>\\n      (function() {\\n        if (document.referrer && document.location.host && document.referrer.match(new RegExp(\\"^https?://\\" + document.location.host))) {\\n          document.getElementById(\\"back-link\\").setAttribute(\\"href\\", document.referrer);\\n        }\\n      })();\\n    </script>\\n  </body>\\n</html>\\n\\n"`,
  error: '<!DOCTYPE html>\n' +
    '<html>\n' +
    '  <head>\n' +
    '    <meta charset="utf-8">\n' +
    '    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">\n' +
    '\n' +
    '    <title>Page Not Found</title>\n' +
    "    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>\n" +
    '    <style>\n' +
    '    body {\n' +
    '      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";\n' +
    '      background: rgb(14, 30, 37);\n' +
    '      color: white;\n' +
    '      overflow: hidden;\n' +
    '      margin: 0;\n' +
    '      padding: 0;\n' +
    '    }\n' +
    '\n' +
    '    h1 {\n' +
    '      margin: 0;\n' +
    '      font-size: 22px;\n' +
    '      line-height: 24px;\n' +
    '    }\n' +
    '\n' +
    '    .main {\n' +
    '      position: relative;\n' +
    '      display: flex;\n' +
    '      flex-direction: column;\n' +
    '      align-items: center;\n' +
    '      justify-content: center;\n' +
    '      height: 100vh;\n' +
    '      width: 100vw;\n' +
    '    }\n' +
    '\n' +
    '    .card {\n' +
    '      position: relative;\n' +
    '      display: flex;\n' +
    '      flex-direction: column;\n' +
    '      width: 75%;\n' +
    '      max-width: 364px;\n' +
    '      padding: 24px;\n' +
    '      background: white;\n' +
    '      color: rgb(14, 30, 37);\n' +
    '      border-radius: 8px;\n' +
    '      box-shadow: 0 2px 4px 0 rgba(14, 30, 37, .16);\n' +
    '    }\n' +
    '\n' +
    '    a {\n' +
    '      margin: 0;\n' +
    '      text-decoration: none;\n' +
    '      font-weight: 600;\n' +
    '      line-height: 24px;\n' +
    '      color: #00ad9f;\n' +
    '    }\n' +
    '\n' +
    '    a svg {\n' +
    '      position: relative;\n' +
    '      top: 2px;\n' +
    '    }\n' +
    '\n' +
    '    a:hover,\n' +
    '    a:focus {\n' +
    '      text-decoration: underline;\n' +
    '      color: #007A70;\n' +
    '    }\n' +
    '\n' +
    '    a:hover svg path{\n' +
    '      fill: #007A70;\n' +
    '    }\n' +
    '\n' +
    '    p:last-of-type {\n' +
    '      margin: 0;\n' +
    '    }\n' +
    '\n' +
    '    </style>\n' +
    '  </head>\n' +
    '  <body>\n' +
    '    <div class="main">\n' +
    '      <div class="card">\n' +
    '        <div class="header">\n' +
    '          <h1>Page Not Found</h1>\n' +
    '        </div>\n' +
    '        <div class="body">\n' +
    "          <p>Looks like you've followed a broken link or entered a URL that doesn't exist on this site.</p>\n" +
    '          <p>\n' +
    '            <a id="back-link" href="/">\n' +
    '              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">\n' +
    '                <path fill="#00ad9f" d="M11.9998836,4.09370803 L8.55809517,7.43294953 C8.23531459,7.74611298 8.23531459,8.25388736 8.55809517,8.56693769 L12,11.9062921 L9.84187871,14 L4.24208544,8.56693751 C3.91930485,8.25388719 3.91930485,7.74611281 4.24208544,7.43294936 L9.84199531,2 L11.9998836,4.09370803 Z"/>\n' +
    '              </svg>\n' +
    '              Back to our site\n' +
    '             </a>\n' +
    '          </p>\n' +
    '        </div>\n' +
    '      </div>\n' +
    '    </div>\n' +
    '    <script>\n' +
    '      (function() {\n' +
    '        if (document.referrer && document.location.host && document.referrer.match(new RegExp("^https?://" + document.location.host))) {\n' +
    '          document.getElementById("back-link").setAttribute("href", document.referrer);\n' +
    '        }\n' +
    '      })();\n' +
    '    </script>\n' +
    '  </body>\n' +
    '</html>\n' +
    '\n',
  options: {
    uri: 'https://www.contributor-covenant.org/version/1/4/code-of-conduct.md',
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      paused: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: false,
    _events: [Object: null prototype] {
      end: [Array],
      close: [Array],
      data: [Function],
      error: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: 'www.contributor-covenant.org',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'www.contributor-covenant.org',
      _readableState: [ReadableState],
      readable: false,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: null,
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      write: [Function: writeAfterFIN],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 60,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kBytesRead)]: 3092,
      [Symbol(kBytesWritten)]: 103,
      [Symbol(connect-options)]: [Object]
    },
    connection: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: 'www.contributor-covenant.org',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'www.contributor-covenant.org',
      _readableState: [ReadableState],
      readable: false,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: null,
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      write: [Function: writeAfterFIN],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 60,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kBytesRead)]: 3092,
      [Symbol(kBytesWritten)]: 103,
      [Symbol(connect-options)]: [Object]
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    headers: {
      'cache-control': 'public, max-age=0, must-revalidate',
      'content-type': 'text/html; charset=utf-8',
      date: 'Fri, 06 Mar 2020 21:45:21 GMT',
      etag: '1502596438-ssl',
      age: '14',
      'content-length': '2785',
      connection: 'close',
      server: 'Netlify',
      'x-nf-request-id': 'ed89988e-f425-4f6b-a7cc-d401ab31609a-10350449'
    },
    rawHeaders: [
      'Cache-Control',
      'public, max-age=0, must-revalidate',
      'Content-Type',
      'text/html; charset=utf-8',
      'Date',
      'Fri, 06 Mar 2020 21:45:21 GMT',
      'Etag',
      '1502596438-ssl',
      'Age',
      '14',
      'Content-Length',
      '2785',
      'Connection',
      'close',
      'Server',
      'Netlify',
      'X-NF-Request-ID',
      'ed89988e-f425-4f6b-a7cc-d401ab31609a-10350449'
    ],
    trailers: {},
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 404,
    statusMessage: 'Not Found',
    client: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: 'www.contributor-covenant.org',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'www.contributor-covenant.org',
      _readableState: [ReadableState],
      readable: false,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: null,
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      write: [Function: writeAfterFIN],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 60,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kBytesRead)]: 3092,
      [Symbol(kBytesWritten)]: 103,
      [Symbol(connect-options)]: [Object]
    },
    _consuming: true,
    _dumped: false,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET /version/1/4/code-of-conduct.md HTTP/1.1\r\n' +
        'host: www.contributor-covenant.org\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      path: '/version/1/4/code-of-conduct.md',
      _ended: true,
      res: [Circular],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      [Symbol(kNeedDrain)]: false,
      [Symbol(isCorked)]: false,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      uri: [Url],
      readable: true,
      writable: true,
      _qs: [Querystring],
      _auth: [Auth],
      _oauth: [OAuth],
      _multipart: [Multipart],
      _redirect: [Redirect],
      _tunnel: [Tunnel],
      _rp_resolve: [Function],
      _rp_reject: [Function],
      _rp_promise: [Promise [Object]],
      _rp_callbackOrig: undefined,
      callback: [Function],
      _rp_options: [Object],
      headers: {},
      setHeader: [Function],
      hasHeader: [Function],
      getHeader: [Function],
      removeHeader: [Function],
      method: 'GET',
      localAddress: undefined,
      pool: {},
      dests: [],
      __isRequestRequest: true,
      _callback: [Function: RP$callback],
      proxy: null,
      tunnel: true,
      setHost: true,
      originalCookieHeader: undefined,
      _disableCookies: true,
      _jar: undefined,
      port: 443,
      host: 'www.contributor-covenant.org',
      path: '/version/1/4/code-of-conduct.md',
      httpModule: [Object],
      agentClass: [Function: Agent],
      agent: [Agent],
      _started: true,
      href: 'https://www.contributor-covenant.org/version/1/4/code-of-conduct.md',
      req: [ClientRequest],
      ntick: true,
      response: [Circular],
      originalHost: 'www.contributor-covenant.org',
      originalHostHeaderName: 'host',
      responseContent: [Circular],
      _destdata: true,
      _ended: true,
      _callbackCalled: true
    },
    toJSON: [Function: responseToJSON],
    caseless: Caseless { dict: [Object] },
    body: '<!DOCTYPE html>\n' +
      '<html>\n' +
      '  <head>\n' +
      '    <meta charset="utf-8">\n' +
      '    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">\n' +
      '\n' +
      '    <title>Page Not Found</title>\n' +
      "    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>\n" +
      '    <style>\n' +
      '    body {\n' +
      '      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";\n' +
      '      background: rgb(14, 30, 37);\n' +
      '      color: white;\n' +
      '      overflow: hidden;\n' +
      '      margin: 0;\n' +
      '      padding: 0;\n' +
      '    }\n' +
      '\n' +
      '    h1 {\n' +
      '      margin: 0;\n' +
      '      font-size: 22px;\n' +
      '      line-height: 24px;\n' +
      '    }\n' +
      '\n' +
      '    .main {\n' +
      '      position: relative;\n' +
      '      display: flex;\n' +
      '      flex-direction: column;\n' +
      '      align-items: center;\n' +
      '      justify-content: center;\n' +
      '      height: 100vh;\n' +
      '      width: 100vw;\n' +
      '    }\n' +
      '\n' +
      '    .card {\n' +
      '      position: relative;\n' +
      '      display: flex;\n' +
      '      flex-direction: column;\n' +
      '      width: 75%;\n' +
      '      max-width: 364px;\n' +
      '      padding: 24px;\n' +
      '      background: white;\n' +
      '      color: rgb(14, 30, 37);\n' +
      '      border-radius: 8px;\n' +
      '      box-shadow: 0 2px 4px 0 rgba(14, 30, 37, .16);\n' +
      '    }\n' +
      '\n' +
      '    a {\n' +
      '      margin: 0;\n' +
      '      text-decoration: none;\n' +
      '      font-weight: 600;\n' +
      '      line-height: 24px;\n' +
      '      color: #00ad9f;\n' +
      '    }\n' +
      '\n' +
      '    a svg {\n' +
      '      position: relative;\n' +
      '      top: 2px;\n' +
      '    }\n' +
      '\n' +
      '    a:hover,\n' +
      '    a:focus {\n' +
      '      text-decoration: underline;\n' +
      '      color: #007A70;\n' +
      '    }\n' +
      '\n' +
      '    a:hover svg path{\n' +
      '      fill: #007A70;\n' +
      '    }\n' +
      '\n' +
      '    p:last-of-type {\n' +
      '      margin: 0;\n' +
      '    }\n' +
      '\n' +
      '    </style>\n' +
      '  </head>\n' +
      '  <body>\n' +
      '    <div class="main">\n' +
      '      <div class="card">\n' +
      '        <div class="header">\n' +
      '          <h1>Page Not Found</h1>\n' +
      '        </div>\n' +
      '        <div class="body">\n' +
      "          <p>Looks like you've followed a broken link or entered a URL that doesn't exist on this site.</p>\n" +
      '          <p>\n' +
      '            <a id="back-link" href="/">\n' +
      '              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">\n' +
      '                <path fill="#00ad9f" d="M11.9998836,4.09370803 L8.55809517,7.43294953 C8.23531459,7.74611298 8.23531459,8.25388736 8.55809517,8.56693769 L12,11.9062921 L9.84187871,14 L4.24208544,8.56693751 C3.91930485,8.25388719 3.91930485,7.74611281 4.24208544,7.43294936 L9.84199531,2 L11.9998836,4.09370803 Z"/>\n' +
      '              </svg>\n' +
      '              Back to our site\n' +
      '             </a>\n' +
      '          </p>\n' +
      '        </div>\n' +
      '      </div>\n' +
      '    </div>\n' +
      '    <script>\n' +
      '      (function() {\n' +
      '        if (document.referrer && document.location.host && document.referrer.match(new RegExp("^https?://" + document.location.host))) {\n' +
      '          document.getElementById("back-link").setAttribute("href", document.referrer);\n' +
      '        }\n' +
      '      })();\n' +
      '    </script>\n' +
      '  </body>\n' +
      '</html>\n' +
      '\n'
  }
}</code></pre>
</details>

**Comment by Yurickh** [comment]
Seem to have been fixed in version v3.1.1

**Comment by RichardLitt** [comment]
Glad this was fixed. @bnb Let me know if it should be reopened, and sorry for the delay in getting back to you!
