### ISSUE TITLE
npmjs version deploys contributor covenant 1.3

### ISSUE THREAD

**Issue by mlinksva** [simonv3/covenant-generator#3]
https://www.npmjs.com/package/covgen

I suppose a version bump and upload to npmjs.com is needed to pick up 1.4 via https://github.com/simonv3/covenant-generator/pull/2 ?

Also I see there's an old version under a previous name at https://www.npmjs.com/package/covenant-generator ... I don't know if npmjs has a mechanism, but if it does it might be nice to note existence of newer versions under different name.

**Comment by simonv3** [comment]
Thanks for opening! I just published 2.1.0 which has the changes for 1.4 in it. 

Yeah, I'll investigate updating the readme to the newer name.

**Comment by RichardLitt** [comment]
I've contacted npm about the redirect. For now, I've bumped to 1.4.

**Comment by RichardLitt** [comment]
From npm:

> Thanks for reaching out. There are a couple of ways the covenant-generator can be redirected to the covgen package.

> You could reach out to the package owner to deprecate thecovenant-generator package on their end When deprecating, they can add the message to point users to the covgen package.

> The other option would be for the owner to reach out to us requesting the package deprecation. Then we would deprecate the package on our end and point user to the covgen package.

**Comment by RichardLitt** [comment]
Looks like @simonv3 needs to contact NPM asking them to do that. Would be the easiest, I think.

**Comment by simonv3** [comment]
contacted.

**Comment by simonv3** [comment]
sweet, deprecated: https://www.npmjs.com/package/covenant-generator
