### ISSUE TITLE
npx covgen does nothing

### ISSUE THREAD

**Issue by asbjornu** [simonv3/covenant-generator#31]
On [contributor-covenant.org](https://www.contributor-covenant.org/), it says:

>Assuming that you have Node.js installed, simply run the following two commands from your project folder:
>
>`npm install -g covgen covgen <your_email_address>`
>
>If you have npm 5.x installed you can run npx covgen <your_email_address> instead of installing globally.

For me, after doing the following:

```sh
$ npx covgen email@example.com
npx: installed 60 in 12.139s
Downloading Contributors Covenant...
Replacing e-mail address...
```

...nothing happens. No files added to disk, nothing. What is `npx covgen <your_email_address>` supposed to do, exactly?

**Comment by bnb** [comment]
Also having this problem right now. Previously it would automatically add CODE_OF_CONDUCT.md, but now it's creating nothing. Additionally, passing the file name (`$ npx covgen hello@bnb.im CODE_OF_CONDUCT.md`) also does nothing. Seems like file writing is broken somehow.

**Comment by betaorbust** [comment]
If you have the package installed locally, it also does nothing. 
I traced it into the `mkdirp-promise` call. It just dies in there. No errors thrown, etc.
If you remove the call to `mkdirp`, it works again (but naturally without the directory creation)

**Comment by stieben** [comment]
The [`mkdirp-promise`](https://www.npmjs.com/package/mkdirp-promise) package has been deprecated.

**Comment by cicorias** [comment]
As there is an outstanding PR, the following will work against that PR branch:
```
npx github.com:betaorbust/covenant-generator <youremail@domain>
```

**Comment by RichardLitt** [comment]
Sorry for the delay all. Merged. Thank you. :)
