### ISSUE TITLE
Deprecated dependency: request

### ISSUE THREAD

**Issue by stieben** [simonv3/covenant-generator#33]
> As of Feb 11th 2020, request is fully deprecated.
> — [npm: request](https://www.npmjs.com/package/request)

Alternative libraries have been suggested: request/request#3143

**Comment by RichardLitt** [comment]
PRs accepted. :)

**Comment by RichardLitt** [comment]
~Looks like this was closed in #32?~ Nevermind.

**Comment by RichardLitt** [comment]
Closed in d15b0c5fbb96877c2652a6d65be4b8f707da8f02. :)
